spring:
  application:
    name: product-service
  datasource:
    url: jdbc:h2:mem:productdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8081

eureka:
  client:
    service-url:
      # defaultZone: http://localhost:8761/eureka/
      defaultZone: http://eureka-server:8761/eureka/ # url that works inside docker 
    register-with-eureka: true  # Tells your service whether it should register itself with the Eureka server. If false, the service won’t appear in the Eureka dashboard
    fetch-registry: true # Tells your service whether it should fetch the list of other services from Eureka. If false, your service cannot discover other services via Eureka.
